name: Command check

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: try some message
        run: |
          echo "::debug::This is a debug message"
          echo "::notice::This is a notice message"
          echo "::warning::This is a warning message"
          echo "::error::This is an error message"
          echo "::notice title=Notice Title::This is a notice message with a title"
          echo "::warning title=Warning Title::This is a warning message with a title"
          echo "::warning title='Warning Title'::This is a warning message 2 with a title"
          echo "::error title=Error Title::This is an error message with a title"
      - name: grep
        run: |
          cat <<EOF | tee /dev/stderr | grep asdf
          12345
          asdf
          zxcv
          EOF
