name: Input empty check
on:
  workflow_dispatch:
    inputs:
      value1:
        description: 'inputs.value1'
        required: false
        type: string
        default: hello
      value2:
        description: 'inputs.value2'
        required: false
        type: string

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Print the value
        run: |
          echo "inputs.value1 = ${{ inputs.value1 }}"
          echo "inputs.value2 = ${{ inputs.value2 }}"
          echo "inputs.value3 (undefined) = ${{ inputs.value3 }}"
          echo "inputs.value1 && 'non-empty' || 'empty' = ${{ inputs.value1 && 'non-empty' || 'empty' }}"
          echo "inputs.value2 && 'non-empty' || 'empty' = ${{ inputs.value2 && 'non-empty' || 'empty' }}"
          echo "inputs.value3 && 'non-empty' || 'empty' = ${{ inputs.value3 && 'non-empty' || 'empty' }}"
          echo "inputs.value1 && 'non-empty' = ${{ inputs.value1 && 'non-empty' }}"
          echo "inputs.value2 && 'non-empty' = ${{ inputs.value2 && 'non-empty' }}"
          echo "inputs.value3 && 'non-empty' = ${{ inputs.value3 && 'non-empty' }}"
          echo "inputs.value1 || 'empty' = ${{ inputs.value1 || 'empty' }}"
          echo "inputs.value2 || 'empty' = ${{ inputs.value2 || 'empty' }}"
          echo "inputs.value3 || 'empty' = ${{ inputs.value3 || 'empty' }}"
          echo "inputs.value1 != '' = ${{ inputs.value1 != '' }}"
          echo "inputs.value2 != '' = ${{ inputs.value2 != '' }}"
          echo "inputs.value3 != '' = ${{ inputs.value3 != '' }}"
      - name: test
        id: test
        run: |
          dummy="this is dummy"
          echo "test=aa bb cc $dummy"  | tee -a $GITHUB_OUTPUT
          printf 'test2=aa bb cc %s' "$dummy" | tee -a $GITHUB_OUTPUT
      - name: print
        run: |
          printf '%s' ${{ steps.test.outputs.test }}
          echo -------------
          printf '%s' ${{ steps.test.outputs.test2 }}

      
