name: Step sumamry example

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: step 1
        run: |
          echo "hello" >> "$GITHUB_STEP_SUMMARY"
          echo '```' >> "$GITHUB_STEP_SUMMARY"
          cat Dockerfile >> "$GITHUB_STEP_SUMMARY"
          echo '```' >> "$GITHUB_STEP_SUMMARY"

      - name: step 2
        run: |
          echo "### Test Summary" >> "$GITHUB_STEP_SUMMARY"
          echo "⚠️ Summary file not found." >> "$GITHUB_STEP_SUMMARY"
          echo "::warning title=warn::NOT FOUND" >> "$GITHUB_STEP_SUMMARY"
          echo '```' >> "$GITHUB_STEP_SUMMARY"
          cat README.md >> "$GITHUB_STEP_SUMMARY"
          echo '```' >> "$GITHUB_STEP_SUMMARY"
